Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using FluentValidation.Results;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using proyecto_ecommerce_deportivo_net.Data;
using proyecto_ecommerce_deportivo_net.Models;
using proyecto_ecommerce_deportivo_net.Models.DTO;
using proyecto_ecommerce_deportivo_net.Models.Validator;

namespace proyecto_ecommerce_deportivo_net.Controllers
{
    public class ClienteController : Controller
    {private readonly ILogger<ClienteController> _logger;

        private readonly ApplicationDbContext _context;

        private readonly UserManager<ApplicationUser> _userManager;

        private readonly SignInManager<ApplicationUser> _signInManager;

        public ClienteController(ILogger<ClienteController> logger, ApplicationDbContext context, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
        {
            _logger = logger;
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }

        [HttpGet]
        public async Task<ActionResult> EditarUsuario(string? id)
        {

            ApplicationUser? usuarioEditar = await _context.Users.FindAsync(id);

            if (usuarioEditar == null)
            {
                Console.Write("No se encontro");
                return NotFound();
            }

            UsuarioEditDTO usuarioEditarDTO = new UsuarioEditDTO();
            usuarioEditarDTO.Id = usuarioEditar.Id;
            usuarioEditarDTO.Nombres = usuarioEditar.Nombres;
            usuarioEditarDTO.Apellidos = usuarioEditar.Apellidos;
            usuarioEditarDTO.Dni = usuarioEditar.Dni;
            return View("EditarUsuario", usuarioEditarDTO);

        }

        [HttpPost]
        public async Task<IActionResult> GuardarUsuarioEditado(UsuarioEditDTO usuarioEditDTO)
        {

            UsuarioEditValidator validator = new UsuarioEditValidator();
            ValidationResult result = validator.Validate(usuarioEditDTO);

            if (result.IsValid)
            {
                ApplicationUser? user = await _context.Users.FindAsync(usuarioEditDTO.Id);
                user.Nombres = usuarioEditDTO.Nombres;
                user.Apellidos = usuarioEditDTO.Apellidos;
                user.Dni = usuarioEditDTO.Dni;

                TempData["MessageActualizandoUsuario"] = "Se Actualizaron exitosamente los datos.";
                _context.Users.Update(user);
                _context.SaveChanges();

                return RedirectToAction("EditarUsuario", new { id = usuarioEditDTO.Id });
            }

            foreach (var failure in result.Errors)
            {
                ModelState.AddModelError(failure.PropertyName, failure.ErrorMessage);
            }
            return View("EditarUsuario", usuarioEditDTO);

        }
    }
}

Controllers/PedidoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using FluentValidation;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.Extensions.Logging;
using proyecto_ecommerce_deportivo_net.Data;
using proyecto_ecommerce_deportivo_net.Models.Validator;
/*LIBRERIAS PARA LA PAGINACION DE LISTAR PRODUCTOS */
using X.PagedList;

/*LIBRERIAS PARA SUBR IMAGENES */
using Firebase.Auth;
using Firebase.Storage;
using System.Web.WebPages;

/*LIBRERIAS NECESARIAS PARA EXPORTAR */
using DinkToPdf;
using DinkToPdf.Contracts;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System.IO;
using System.Linq;
using OfficeOpenXml.Table;
using proyecto_ecommerce_deportivo_net.Models;
using proyecto_ecommerce_deportivo_net.Models.Entity;
using Microsoft.AspNetCore.Identity;

using System.Drawing;

namespace proyecto_ecommerce_deportivo_net.Controllers
{
    public class PedidoController : Controller
    {
        private readonly ILogger<PedidoController> _logger;

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;

        // Objeto para la exportación
        private readonly IConverter _converter;

        public PedidoController(ILogger<PedidoController> logger, UserManager<ApplicationUser> userManager, ApplicationDbContext context, IConverter converter)
        {
            _logger = logger;
            _userManager = userManager;
            _context = context;
            ModelState.Clear();


            _converter = converter; // PARA EXPORTAR
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }

        /// <summary>
        /// Obtiene una lista paginada de pedidos. Si no se especifica un número de página, 
        /// se asume la primera página. Cada página muestra un máximo de 2 pedidos. 
        /// Esta función me ayuda a entender cómo implementar la paginación en ASP.NET Core 
        /// y cómo manejar parámetros opcionales en los controladores.
        /// </summary>
        public ActionResult ListaDePedidos(int? page)
        {
            int pageNumber = (page ?? 1); // Si no se especifica la página, asume la página 1
            int pageSize = 3; // maximo 3 pedidos por pagina


            pageNumber = Math.Max(pageNumber, 1);// Con esto se asegura de que pageNumber nunca sea menor que 1

            IPagedList listaPaginada = _context.DataPedido.ToPagedList(pageNumber, pageSize);

            return View("ListaDePedidos", listaPaginada);
        }


        /* metodos para exportar en pdf y excel desde aqui para abajo */
        public IActionResult ExportarPedidosEnPDF()
        {
            try
            {
                var pedidos = _context.DataPedido.ToList();
                var html = @"
            <html>
                <head>
                <meta charset='UTF-8'>
                    <style>
                        table {
                            width: 100%;
                            border-collapse: collapse;
                        }
                        th, td {
                            border: 1px solid black;
                            padding: 8px;
                            text-align: left;
                        }
                        th {
                            background-color: #f2f2f2;
                        }
                        img.logo {
                            position: absolute;
                            top: 0;
                            right: 0;
                            border-radius:50%;
                            height:3.3rem;
                            width:3.3rem;
                        }

                        h1 {
                            color: #40E0D0; /* Color celeste */
                        }
                    </style>
                </head>
                <body>
                    <img src='https://firebasestorage.googleapis.com/v0/b/proyectos-cb445.appspot.com/o/img_logo_athletix.png?alt=media&token=a32e429b-4ece-45d2-bf00-85a8f9081a9c&_gl=1*14iryjj*_ga*MTcyOTkyMjIwMS4xNjk2NDU2NzU2*_ga_CW55HF8NVT*MTY5ODAxNDc2Mi4yLjEuMTY5ODAxNDg0Ny40OC4wLjA.' alt='Logo' width='100' class='logo'/>
                    <h1>Reporte de Pedidos</h1>
                    <table>
                        <tr>
                            <th>ID</th>
                            <th>UserID</th>
                            <th>Total (en soles)</th>
                       
                            <th>Status</th>
                        </tr>";

                foreach (var pedido in pedidos)
                {

                    html += $@"
                <tr>
                    <td>{pedido.ID}</td>
                    <td>{pedido.UserID}</td>
                    <td>{pedido.Total}</td>
                 
                    <td>{pedido.Status}</td>
   
                </tr>";
                }

                html += @"
                    </table>
                </body>
            </html>";

                var globalSettings = new GlobalSettings
                {
                    ColorMode = ColorMode.Color,
                    Orientation = Orientation.Portrait,
                    PaperSize = PaperKind.A4,
                };
                var objectSettings = new ObjectSettings { HtmlContent = html };
                var pdf = new HtmlToPdfDocument()
                {
                    GlobalSettings = globalSettings,
                    Objects = { objectSettings }
                };
                var file = _converter.Convert(pdf);

                return File(file, "application/pdf", "Pedidos.pdf");

            }
            catch (Exception ex)
            {
                // Loguear el error para obtener más detalles
                _logger.LogError(ex, "Error al exportar Pedidos a PDF");
                // Retornar un mensaje de error al usuario
                return StatusCode(500, "Ocurrió un error al exportar los Pedidos a PDF. Por favor, inténtelo de nuevo más tarde.");
            }
        }


        public IActionResult ExportarPedidosEnExcel()
        {
            try
            {
                var resultados = (from p in _context.DataPedido
                                  join d in _context.DataDetallePedido on p.ID equals d.pedido.ID
                                  join pa in _context.DataPago on p.pago.Id equals pa.Id
                                  select new
                                  {
                                      IDPedido = p.ID,
                                      UserID = p.UserID,
                                      Total = p.Total,
                                      Status = p.Status,
                                      FechaDePago = pa.PaymentDate,
                                      NombreTarjeta = pa.NombreTarjeta,
                                      //Ultimos4DigitosTarjeta = pa.NumeroTarjeta.Length > 4 ? pa.NumeroTarjeta.Substring(pa.NumeroTarjeta.Length - 4) : pa.NumeroTarjeta,
                                      DigitosTarjeta = pa.NumeroTarjeta,
                                      MontoPagado = pa.MontoTotal,
                                      IDProducto = d.Producto.id,
                                      Cantidad = d.Cantidad,
                                      PrecioUnitario = d.Precio
                                  }).ToList();

                using var package = new ExcelPackage();
                var worksheet = package.Workbook.Worksheets.Add("Pedidos");

                // Agregando un título arriba de la tabla
                worksheet.Cells[1, 1].Value = "Reporte de Pedidos";
                worksheet.Cells[1, 1].Style.Font.Size = 20;
                worksheet.Cells[1, 1].Style.Font.Bold = true;

                // Cargar los datos en la fila 3 para dejar espacio para el título de Reporte de Pedidos
                worksheet.Cells[3, 1].LoadFromCollection(resultados, true);

                // Dar formato a la tabla Reporte de Pedidos
                var dataRange = worksheet.Cells[2, 1, worksheet.Dimension.End.Row, worksheet.Dimension.End.Column];
                var table = worksheet.Tables.Add(dataRange, "Pedidos");
                table.ShowHeader = true;
                table.TableStyle = TableStyles.Light6;

                // Estilo para los encabezados de las columnas 
                worksheet.Cells[3, 1, 3, worksheet.Dimension.End.Column].Style.Font.Bold = true;
                worksheet.Cells[3, 1, 3, worksheet.Dimension.End.Column].Style.Fill.PatternType = OfficeOpenXml.Style.ExcelFillStyle.Solid;
                worksheet.Cells[3, 1, 3, worksheet.Dimension.End.Column].Style.Fill.BackgroundColor.SetColor(System.Drawing.Color.LightBlue);
                worksheet.Cells[3, 1, 3, worksheet.Dimension.End.Column].Style.Font.Color.SetColor(System.Drawing.Color.DarkBlue);

                // Ajustar el ancho de las columnas automáticamente
                worksheet.Cells.AutoFitColumns();

                var stream = new MemoryStream();
                package.SaveAs(stream);

                return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Pedidos.xlsx");
            }
            catch (Exception ex)
            {
                // Loguear el error para obtener más detalles
                _logger.LogError(ex, "Error al exportar pedidos a Excel");
                // Retornar un mensaje de error al usuario
                return StatusCode(500, "Ocurrió un error al exportar los pedidos a Excel. Por favor, inténtelo de nuevo más tarde.");
            }
        }

Controllers/TipoCambioController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using proyecto_ecommerce_deportivo_net.Integrations;
using proyecto_ecommerce_deportivo_net.Models;
using proyecto_ecommerce_deportivo_net.DTO;
using proyecto_ecommerce_deportivo_net.Data;

namespace proyecto_ecommerce_deportivo_net.Controllers
{

    public class TipoCambioController : Controller
    {
        private readonly ILogger<TipoCambioController> _logger;
        private readonly CurrencyExchangeApiIntegration _currency;

        public TipoCambioController(ILogger<TipoCambioController> logger,
        CurrencyExchangeApiIntegration currency)
        {
            _logger = logger;
            _currency = currency;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Exchange(TipoCambioDTO? tipoCambio)
        {
            double rate = await _currency.GetExchangeRate(tipoCambio.From, tipoCambio.To);
            var cambio = tipoCambio.Cantidad * rate;
            ViewData["From"] = tipoCambio.From;
            ViewData["To"] = tipoCambio.To;
            ViewData["rate"] = rate;
            ViewData["cambio"] = cambio;
            return View("Index");
        }

       

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using proyecto_ecommerce_deportivo_net.Models
@using System.Collections.Generic;
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="icon" href="~/images/logo.png" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/proyecto_ecommerce_deportivo_net.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://unpkg.com/swiper@8/swiper-bundle.min.css">
    <link rel="stylesheet" href="~/css/layout.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    
    <link rel="stylesheet" href="~/css/mensajes.css" />
</head>

@{
    ApplicationUser myidentity = null;
    IList<string> roles = new List<string>();

    if (User.Identity.IsAuthenticated)
    {
        myidentity = await UserManager.GetUserAsync(User);
        if (myidentity != null)
        {
            roles = await UserManager.GetRolesAsync(myidentity);
        }
    }
}


<body>
    <!---------------------------- header section stars ---------------------------->
    <header class="header">
        <div id="menu-btn" class="fas fa-bars"></div>
        <a class="logo" style="text-decoration: none;" asp-area="" asp-controller="Home" asp-action="Index">
            <img src="~/images/logo.png" alt="Logo" style="height: 40px; width: 40px; border-radius:50%;"
                id="imgLogoEmpresa">
            <span id="span-logo">AthletiX</span>
        </a>
        <nav class="navbar">
            @if (!SignInManager.IsSignedIn(User) || !roles.Contains("Admin"))
            {
                <a class="nav-link" asp-area="" asp-controller="NoCliente" asp-action="Catalogo">Catálogo de Productos</a>
                <a class="nav-link" asp-area="" asp-controller="Contacto" asp-action="Index">Contáctanos</a>
                <a class="nav-link" asp-area="" asp-controller="TipoCambio" asp-action="Index">Tipo de cambio</a>
            }

            @if (roles.Contains("Admin"))
            {
                <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="ListaDeProductos">Lista De
                    Productos</a>
                <a class="nav-link" asp-area="" asp-controller="Pedido" asp-action="ListaDePedidos">Lista De
                    Pedidos</a>
                <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="ListaDeUsuarios">Lista De
                    Usuarios</a>

                <a class="nav-link" asp-area="" asp-controller="Estadistica" asp-action="Index">Estadisticas</a>
            }
        </nav>
        <div class="iconos">
            @if (SignInManager.IsSignedIn(User))
            {
                if (!roles.Contains("Admin"))
                {
                    <div class="icono-login">
                        <a class="fas fa-shopping-bag" style="text-decoration: none;" asp-area="" asp-controller="MisPedidos"
                            asp-action="MisPedidos"></a>
                    </div>
                    <div class="icono-user">
                        <a class="fas fa-shopping-cart" style="text-decoration: none;" asp-area="" asp-controller="Carrito"
                            asp-action="Index"></a>
                    </div>
                    <style>
                        @@media (max-width: 600px) {
                            #span-logo {
                                display: none;
                            }
                        }
                    </style>
                }
                <div class="icono-login">
                    <!--<a class="fas fa-user" style="text-decoration: none;" asp-controller="Cliente"
                                asp-action="EditarUsuario" asp-route-id="@UserManager.GetUserId(User)"></a>-->

                    <a class="fas fa-user" style="text-decoration: none;" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage"></a>
                </div>
                @*
            <div class="icono-logout">
            <a class="fas fa-sign-out-alt" style="text-decoration: none;" asp-area="Identity"
            asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home",
            new { area = "" })">
            </a>
            </div>
            *@
                <div class="icono-logout">
                    <button id="mostrarTarjeta">
                        <a class="fas fa-sign-out-alt" style="text-decoration: none;"></a>
                    </button>
                </div>

                <div class="tarjeta" id="tarjeta">
                    <div id="tarjeta-sesion">
                        <div id="cerrar-sesion">
                            <h1>¿Deseas cerrar sesión?</h1>
                        </div>
                        <div id="botones">
                            <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout"
                                asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })" method="post">
                                <button type="submit">Cerrar Sesión</button>
                            </form>
                            <button id="cerrarTarjeta">Mantener Sesión</button>
                        </div>
                    </div>
                </div>

                <script src="~/js/script.js"></script>

            }
            else
            {
                <div class="icono-login">
                    <a class="fas fa-user-plus" style="text-decoration: none;" asp-area="Identity"
                        asp-page="/Account/Register"></a>
                </div>
                <div class="icono-logout">
                    <a class="fas fa-sign-in-alt" style="text-decoration: none;" asp-area="Identity"
                        asp-page="/Account/Login"></a>
                </div>
                <style>
                    @@media (max-width: 600px) {
                        #imgLogoEmpresa {
                            display: none;
                        }
                    }
                </style>
            }
        </div>
    </header>
    <!---------------------------- header section ends ---------------------------->
    <div class="container-fluid">
        <main role="main" class="p-0">
            @RenderBody()
        </main>
    </div>
    <!---------------------------- footer section stars  ---------------------------->
    <section class="footer">
        <div class="box-container">
            <div class="box">
                <h3 class="footer-h3">Enlaces Rápidos</h3>
                <a id="detalles-footer" asp-area="" asp-controller="Home" asp-action="Index"> <i
                        class="fas fa-arrow-right"></i>
                    Principal</a>
                @if (!SignInManager.IsSignedIn(User) || !roles.Contains("Admin"))
                {
                    <a id="detalles-footer" asp-area="" asp-controller="NoCliente" asp-action="Catalogo"> <i
                            class="fas fa-arrow-right"></i>
                        Catálogo de Productos </a>
                }
                <a id="detalles-footer" asp-area="" asp-controller="Home" asp-action="Index"> <i
                        class="fas fa-arrow-right"></i>
                    Descripción</a>
                <a id="detalles-footer" asp-area="" asp-controller="Home" asp-action="Index"> <i
                        class="fas fa-arrow-right"></i>
                    Misión y Visión </a>
                @if (!SignInManager.IsSignedIn(User) || !roles.Contains("Admin"))
                {
                    <a id="detalles-footer" asp-area="" asp-controller="Contacto" asp-action="Index"> <i
                            class="fas fa-arrow-right"></i>
                        Contáctanos </a>
                }
            </div>

            <div class="box">
                <h3>Datos De Contacto</h3>
                <a id="detalles-footer"> <i class="fas fa-phone"></i> +51 927 572 267 </a>
                <a id="detalles-footer"> <i class="fas fa-envelope"></i> jesus_soria@usmp.pe </a>
                <a id="detalles-footer"> <i class="fas fa-map-marker-alt"></i> La Molina, Av. la Fontana 1250, Lima
                    15024 </a>
            </div>

            <div class="box">
                <h3>Redes</h3>
                <a id="detalles-footer" href="https://www.facebook.com/profile.php?id=61552031275470"> <i
                        class="fab fa-facebook-f"></i>
                    Facebook </a>
                <a id="detalles-footer" href="https://api.whatsapp.com/send?phone=927572267" target="_blank"><i
                        class="fab fa-whatsapp"></i>
                    WhatsApp</a>

                <h3 style="margin-top: 2rem;">Legal</h3>
                <a id="detalles-footer"
                    href="https://usmppe-my.sharepoint.com/:b:/g/personal/kristell_flores_usmp_pe/EYbpg6ow49NOrrfsEipAhUMBLP58bki3_0xgGhMoMD2Gsg?e=IZjH3n">
                    <i class="fa fa-gavel"></i> Términos y Condiciones </a>
                <a id="detalles-footer"
                    href="https://usmppe-my.sharepoint.com/:b:/g/personal/kristell_flores_usmp_pe/EawhNQa8nnFIvtA-mxdpmEABJECIjW4e5Y5DpHquDN5igQ?e=nUcCWC">
                    <i class="fa fa-lock"></i> Politicas de privacidad </a>
            </div>

            <div class="box">
                <h3>Desarrolladores</h3>
                <a id="detalles-footer"> <i class="fas fa-laptop-code"></i> Matias N Araujo Vera </a>
                <a id="detalles-footer"> <i class="fas fa-cogs"></i> Yasser M. Avalos Montero </a>
                <a id="detalles-footer"> <i class="fas fa-laptop"></i> Kristell Y. Flores Huamani </a>
                <a id="detalles-footer"> <i class="fas fa-user-cog"></i> Jesús A. Soria Llantoy </a>
            </div>
        </div>
        <div class="credit"> @@Copyright - Todos los derechos reservados - Grupo ROJO! </div>
    </section>
    <!---------------------------- footer section ends  ---------------------------->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://unpkg.com/swiper@8/swiper-bundle.min.js"></script>
    <script>
        let menu = document.querySelector('#menu-btn');
        let navbar = document.querySelector('.navbar');

        menu.onclick = () => {
            menu.classList.toggle('fa-times');
            navbar.classList.toggle('active');
        }

        /**/

    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>