Models/Entity/Contacto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations.Schema;

namespace proyecto_ecommerce_deportivo_net.Models.Entity {

     [Table("t_contacto")]
    public class Contacto {
        //EL SIGNO DE INTERROGACION ES PARA DEJAR VALORES NULOS
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column("id")]
        public int Id { get; set; }

        [Column("Nombre")]
        public string? Nombre { get; set; }

        [Column("Email")]
        public string? Email { get; set; }

        [Column("Phone")]
        public string? Phone { get; set; }

        [Column("Asunto")]
        public string? Asunto { get; set; }

        [Column("Mensaje")]
        public string? Mensaje { get; set; }
    }
}

Controllers/UI/ContactoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using proyecto_ecommerce_deportivo_net.Models;
using proyecto_ecommerce_deportivo_net.Data;
using proyecto_ecommerce_deportivo_net.Models.Entity;
using proyecto_ecommerce_deportivo_net.Models.Service;

namespace proyecto_ecommerce_deportivo_net.Controllers.UI
{
    public class ContactoController : Controller
    {
        private readonly ContactanosService _contactanosService;

        private readonly IMyEmailSender _emailSender;

        public ContactoController(ContactanosService contactanosService, IMyEmailSender emailSender)
        {
            _contactanosService = contactanosService;

            _emailSender = emailSender;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Contacto objContacto)
        {
            if (!ModelState.IsValid)
            {
                // Manejar errores de validación, si es necesario
                return BadRequest(ModelState);
            }

            await _contactanosService.CreateOrUpdate(objContacto);

            var message = $"Estimado(a) {objContacto.Nombre}, te estaremos contactando pronto";
            TempData["MessageCONTACTO"] = message;

            var message1 = $@"
            Estimado(a) {objContacto.Nombre},

            ¡Gracias por ponerte en contacto con nosotros!

            Hemos recibido tu solicitud y uno de nuestros representantes se pondrá en contacto contigo a la brevedad. 
            Valoramos tu interés y nos esforzamos por responder todas las consultas lo más rápido posible.

            Tu mensaje fue:
            {objContacto.Mensaje}

            Tu Número Telefónico fue: {objContacto.Phone}
            Tu Correo electronico fue: {objContacto.Email}

            Mientras tanto, te invitamos a explorar nuestro sitio web o nuestras redes sociales para obtener más información sobre nuestros productos y servicios.

            ¡Gracias por elegirnos!

            Saludos cordiales,

            [La Empresa Deportiva AthletiX]
        ";

            //await _emailSender.SendEmailAsync(objContacto.Email, "Gracias por contactarnos", message);
            await _emailSender.SendEmailAsync(objContacto.Email, "" + objContacto.Asunto, message1);

            //return Ok(objContacto);
            return View("~/Views/Contacto/Index.cshtml");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/Contacto/Index.cshtml
@model proyecto_ecommerce_deportivo_net.Models.Entity.Contacto
@{
    ViewData["Title"] = "Contáctanos";
}
<link rel="stylesheet" href="~/css/contacto.css" />
<section class="contact" id="contact">
    <h1 class="heading">
        <span>Contáctanos</span>
    </h1>
    <div class="row">
        <iframe class="map"
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3901.5854482620507!2d-76.94473582703425!3d-12.072018542367156!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9105c6e79034dc63%3A0x393610bdc506718b!2sFacultad%20de%20Ingenier%C3%ADa%20y%20Arquitectura%20-%20USMP!5e0!3m2!1ses!2spe!4v1698767104135!5m2!1ses!2spe"
            allowfullscreen="" loading="lazy"></iframe>

        <form asp-controller="Contacto" asp-action="Create" method="post">
            <h3>Ponerse En Contacto</h3>
            <input type="text" placeholder="Nombre Completo" class="box" id="Nombre" name="Nombre" required>
            <input type="email" placeholder="Correo electrónico" class="box" id="Email" name="Email" required>
            <input type="number" placeholder="Número de Teléfono" class="box" id="Phone" name="Phone" required>
            <input type="text" placeholder="Asunto" class="box" id="Asunto" name="Asunto" required>
            <textarea placeholder="Mensaje" class="box" rows="10" cols="30" id="Mensaje" name="Mensaje"
                required></textarea>
            <input type="submit" value="Enviar Mensaje" class="btn">
        </form>

        @if (TempData["MessageCONTACTO"] != null)
        {
            <div class="alert alert-success" id="MensajesVerdeRojo">
                @TempData["MessageCONTACTO"]
            </div>
        }
    </div>
</section>
<!---------------------------- contact section ends  ---------------------------->