Models/Entity/CarritoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace proyecto_ecommerce_deportivo_net.Models.Entity
{
    public class CarritoViewModel
    {
        public List<Proforma> Items { get; set; }
        public double Subtotal { get; set; }
        public double Descuento { get; set; }
        public double Total { get; set; }
    }
}

Controllers/CarritoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using proyecto_ecommerce_deportivo_net.Data;
using proyecto_ecommerce_deportivo_net.Models;
using proyecto_ecommerce_deportivo_net.Models.Entity;

using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Npgsql;

namespace proyecto_ecommerce_deportivo_net.Controllers
{
    public class CarritoController : Controller
    {
        private readonly ILogger<CarritoController> _logger;

        private ApplicationDbContext _context;

        /* para el cliente o administrador iniciado */

        private readonly UserManager<ApplicationUser> _userManager;

        private readonly SignInManager<ApplicationUser> _signInManager;

        private readonly ICarritoService _carritoService;
        public CarritoController(ILogger<CarritoController> logger, ApplicationDbContext context,
                UserManager<ApplicationUser> userManager,
                SignInManager<ApplicationUser> signInManager, ICarritoService carritoService)
        {
            _logger = logger;


            _context = context;

            /* variables para el objeto iniciado */
            _userManager = userManager;
            _signInManager = signInManager;

            _carritoService = carritoService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var userId = _userManager.GetUserName(User);
                var items = await _carritoService.ObtenerItems(userId);
                var subtotal = await _carritoService.ObtenerSubtotal(userId);
                var descuento = await _carritoService.ObtenerDescuento(userId);
                var total = await _carritoService.ObtenerTotal(userId);

                var viewModel = new CarritoViewModel
                {
                    Items = items.ToList(),
                    Subtotal = subtotal,
                    Descuento = descuento,
                    Total = total+descuento
                };

                return View(viewModel);
            }
            catch (NpgsqlException ex)
            {
                _logger.LogError(ex, "Un error ocurrió mientras se interactuaba con la base de datos.");
                return View("DatabaseError");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Un error inesperado ocurrió mientras se obtenía el índice del carrito.");
                return View("Error");
            }
        }

        public async Task<IActionResult> QuitarDelCarrito(int id)
        {
            try
            {
                var userId = _userManager.GetUserName(User);
                if (userId == null)
                {
                    throw new Exception("User is not authenticated.");
                }
                var result = await _carritoService.QuitarDelCarrito(id, userId);
                if (result)
                {
                    return RedirectToAction("Index", "Carrito");
                }
                return View("Error");
            }
            catch (NpgsqlException ex)
            {
                _logger.LogError(ex, "Un error ocurrió mientras se interactuaba con la base de datos.");
                return View("DatabaseError");
            }
            catch (EndOfStreamException ex)
            {
                _logger.LogError(ex, "Intento de leer más allá del final del flujo.");
                return View("StreamError");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, $"Un error ocurrió mientras se intentaba quitar el ítem con ID {id} del carrito.");
                return View("Error");
            }
        }

        [HttpPost]
        public async Task<IActionResult> ActualizarCantidad(int id, int cantidad)
        {
            try
            {
                var userId = _userManager.GetUserName(User);
                var result = await _carritoService.ActualizarCantidad(id, cantidad, userId);
                if (result)
                {
                    return RedirectToAction("Index", "Carrito");
                }
                return View("Error");

            }
            catch (NpgsqlException ex)
            {
                _logger.LogError(ex, "Un error ocurrió mientras se interactuaba con la base de datos.");
                return View("DatabaseError");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, $"Un error ocurrió mientras se actualizaba la cantidad del ítem con ID {id}.");
                return View("Error");
            }
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/NoClienteController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using proyecto_ecommerce_deportivo_net.Data;
using proyecto_ecommerce_deportivo_net.Models;
using proyecto_ecommerce_deportivo_net.Models.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;

namespace proyecto_ecommerce_deportivo_net.Controllers
{
    public class NoClienteController : Controller
    {
        private readonly ILogger<NoClienteController> _logger;
        private ApplicationDbContext _context;

        /* para el cliente o administrador iniciado */

        private readonly UserManager<ApplicationUser> _userManager;

        private readonly SignInManager<ApplicationUser> _signInManager;
        public NoClienteController(ILogger<NoClienteController> logger, ApplicationDbContext context,
                UserManager<ApplicationUser> userManager,
                SignInManager<ApplicationUser> signInManager)
        {
            _logger = logger;
            _context = context;

            /* variables para el objeto iniciado */
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [HttpGet]
        public IActionResult Catalogo()
        {
            var productos = from o in _context.Producto select o;
            return View(productos.ToList());
        }

        [HttpGet] /* este index lo hice de prueba para arreglar el problema del carrusel NO TOCARLO */
        public IActionResult Index()
        {
            return View();
        }


        public async Task<IActionResult> BuscarProducto(string query)
        {
            try
            {
                // Si no hay una consulta de búsqueda, retorna todos los productos.
                if (string.IsNullOrWhiteSpace(query))
                {
                    var todosLosProductos = await _context.Producto.ToListAsync();
                    return View("Catalogo", todosLosProductos);
                }

                // Convierte la consulta de búsqueda a mayúsculas para la comparación.
                query = query.ToUpper();

                // Busca productos que coincidan con la consulta de búsqueda.
                var productos = await _context.Producto
                    .Where(p => p.Nombre.ToUpper().Contains(query))
                    .ToListAsync();

                // Si no se encontraron productos, establece un mensaje en TempData.
                if (!productos.Any())
                {
                    TempData["MessageDeRespuesta"] = "No se encontraron productos que coincidan con la búsqueda.";
                }
                else
                {
                    TempData["MessageDeRespuesta1"] = "Si se encontraron productos que coincidan con la búsqueda.";
                }
                // Retorna la vista Catalogo con la lista de productos.
                return View("Catalogo", productos);
            }
            catch (Exception ex)
            {
                // En caso de error, establece un mensaje en TempData y retorna una lista vacía a la vista.
                TempData["MessageDeRespuesta"] = "Ocurrió un error al buscar productos. Por favor, inténtalo de nuevo más tarde.";
                return View("Catalogo", new List<Producto>());
            }
        }

        public async Task<IActionResult> DetalleProducto(int? id)
        {
            Producto objProduct = await _context.Producto.FindAsync(id);
            if (objProduct == null)
            {
                return NotFound();
            }
            return View(objProduct);
        }

        [HttpPost] // Asegúrate de que es un método POST
        public async Task<IActionResult> AddCarrito(int id, int cantidad)
        {
            var userID = _userManager.GetUserName(User); //sesion

            if (userID == null)
            {
                // no se ha logueado
                TempData["MessageLOGUEARSE"] = "Por favor, inicie sesión antes de agregar un producto.";
                return View("~/Views/Home/Index.cshtml");
            }
            else
            {
                // ya está logueado
                var producto = await _context.Producto.FindAsync(id);

                // Verificar si hay suficiente stock del producto
                if (producto.Stock < cantidad)
                {
                    TempData["ErrorSTOCK"] = $"No hay suficiente stock disponible. Solo hay {producto.Stock} unidades en stock.";
                    return RedirectToAction("DetalleProducto", new { id = id }); // Esto redirige a la vista DetalleProducto si no se cumple la condicion
                }

                // Buscar una proforma existente para el usuario y producto
                var proformaExistente = await _context.DataCarrito
                    .Where(p => p.UserID == userID && p.Producto.id == id && p.Status == "PENDIENTE")
                    .FirstOrDefaultAsync();

                if (proformaExistente != null)
                {
                    // Si existe, actualizar la cantidad
                    proformaExistente.Cantidad = cantidad;
                }
                else
                {
                    // Si no existe, crear una nueva proforma
                    Proforma proforma = new Proforma
                    {
                        Producto = producto,
                        Precio = producto.Precio,
                        Cantidad = cantidad, // Usa la cantidad pasada desde el formulario
                        UserID = userID,
                        Status = "PENDIENTE" // asegurandome con esto de que el estado es pendiente
                    };
                    _context.Add(proforma);
                }

                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Carrito");
            }
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/UI/CarritoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using proyecto_ecommerce_deportivo_net.Data;
using proyecto_ecommerce_deportivo_net.Models;
using proyecto_ecommerce_deportivo_net.Models.Entity;

using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Npgsql;

namespace proyecto_ecommerce_deportivo_net.Controllers.UI
{
    public class CarritoController : Controller
    {
        private readonly ILogger<CarritoController> _logger;

        private ApplicationDbContext _context;

        /* para el cliente o administrador iniciado */

        private readonly UserManager<ApplicationUser> _userManager;

        private readonly SignInManager<ApplicationUser> _signInManager;

        private readonly ICarritoService _carritoService;
        public CarritoController(ILogger<CarritoController> logger, ApplicationDbContext context,
                UserManager<ApplicationUser> userManager,
                SignInManager<ApplicationUser> signInManager, ICarritoService carritoService)
        {
            _logger = logger;


            _context = context;

            /* variables para el objeto iniciado */
            _userManager = userManager;
            _signInManager = signInManager;

            _carritoService = carritoService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var userId = _userManager.GetUserName(User);
                var items = await _carritoService.ObtenerItems(userId);
                var subtotal = await _carritoService.ObtenerSubtotal(userId);
                var descuento = await _carritoService.ObtenerDescuento(userId);
                var total = await _carritoService.ObtenerTotal(userId);

                var viewModel = new CarritoViewModel
                {
                    Items = items.ToList(),
                    Subtotal = subtotal,
                    Descuento = descuento,
                    Total = total+descuento
                };

                return View(viewModel);
            }
            catch (NpgsqlException ex)
            {
                _logger.LogError(ex, "Un error ocurrió mientras se interactuaba con la base de datos.");
                return View("DatabaseError");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Un error inesperado ocurrió mientras se obtenía el índice del carrito.");
                return View("Error");
            }
        }

        public async Task<IActionResult> QuitarDelCarrito(int id)
        {
            try
            {
                var userId = _userManager.GetUserName(User);
                if (userId == null)
                {
                    throw new Exception("User is not authenticated.");
                }
                var result = await _carritoService.QuitarDelCarrito(id, userId);
                if (result)
                {
                    return RedirectToAction("Index", "Carrito");
                }
                return View("Error");
            }
            catch (NpgsqlException ex)
            {
                _logger.LogError(ex, "Un error ocurrió mientras se interactuaba con la base de datos.");
                return View("DatabaseError");
            }
            catch (EndOfStreamException ex)
            {
                _logger.LogError(ex, "Intento de leer más allá del final del flujo.");
                return View("StreamError");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, $"Un error ocurrió mientras se intentaba quitar el ítem con ID {id} del carrito.");
                return View("Error");
            }
        }

        [HttpPost]
        public async Task<IActionResult> ActualizarCantidad(int id, int cantidad)
        {
            try
            {
                var userId = _userManager.GetUserName(User);
                var result = await _carritoService.ActualizarCantidad(id, cantidad, userId);
                if (result)
                {
                    return RedirectToAction("Index", "Carrito");
                }
                return View("Error");

            }
            catch (NpgsqlException ex)
            {
                _logger.LogError(ex, "Un error ocurrió mientras se interactuaba con la base de datos.");
                return View("DatabaseError");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, $"Un error ocurrió mientras se actualizaba la cantidad del ítem con ID {id}.");
                return View("Error");
            }
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/Carrito/Index.cshtml
@model proyecto_ecommerce_deportivo_net.Models.Entity.CarritoViewModel
@inject proyecto_ecommerce_deportivo_net.Integrations.CurrencyExchangeApiIntegration CurrencyExchangeService

@using System.Collections.Generic;
@using Microsoft.AspNetCore.Mvc.ViewFeatures
@{
    ViewData["Title"] = "Carrito de compras";
    var totalEnUSD = Model.Total * await CurrencyExchangeService.GetExchangeRate("PEN", "USD");

    // aquí leo el posible mensaje enviado por TempData
    var mensajeConsola = TempData["MensajeConsola"] as string;
}

<Style>
    @@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@100;300;400;500;600&display=swap');

    :root {
        --my-blue: #0074E4;
        --light-my-blue: #6FA6FF;
        /* Aquí defines el tono más claro */
        --celeste: #40E0D0;
        --light-celeste: hsl(177, 72%, 70%);
        --amarillo: #f9d806;
        --light-amarillo: #ffee80;
        --rojo: #FF0000;
        --light-rojo: #FFAFAF;
        --verde: #369681;
        --light-verde: #00B050;
        --black: #130f40;
        --light-color: #666;
        --border: .1rem solid rgba(0, 0, 0, .1);
        --box-shadow: 0 .5rem 1rem rgba(0, 0, 0, .1);
    }

    * {
        font-family: 'Poppins', sans-serif;
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        outline: none;
        border: none;
        text-decoration: none;
        transition: all .2s linear;
    }

    body {
        margin-bottom: 0px;
    }

    html {
        font-size: 50.5%;
        overflow-x: hidden;
        scroll-padding-top: 7rem;
        scroll-behavior: smooth;
    }

    section {
        padding: 2rem 6%;
    }

    /* header */


    .heading {
        text-align: center;
        padding-bottom: 2rem;
        font-size: 4.5rem;
        color: var(--black);
    }

    .heading span {
        position: relative;
        z-index: 0;
    }

    .heading span::before {
        content: '';
        position: absolute;
        bottom: 1rem;
        left: 0;
        height: 100%;
        width: 100%;
        z-index: -1;
        background: var(--celeste);
        clip-path: polygon(0 90%, 100% 80%, 100% 100%, 0% 100%);
        /* CON ESTO PONGO LA LINEA AMARILLA ABAJO DE LA PALABRA Vehicles de color amarillo */
    }

    /* hasta aca arriba */
    .btn {
        display: inline-block;
        margin-top: 1rem;
        border-radius: .5rem;
        background: var(--light-celeste);
        color: var(--black);
        font-weight: 500;
        font-size: 1.7rem;
        cursor: pointer;
        padding: .8rem 3rem;
    }

    .btn:hover {
        background: var(--celeste);
    }

    /*------- cart item  --------*/

    .carrito {
        margin-top: -100px;
        /* esto hace que el carrito este mas arriba restandole el espaciado del navbar con el titulo del carrito */
    }

    .cart-page {
        margin: 80px auto;
    }


    table {
        width: 100%;
        border-collapse: collapse;
    }

    .cart-info {
        display: flex;
        flex-wrap: wrap;
    }

    th {
        text-align: left;
        font-size: 15px;
        padding: 5px;
        color: #fff;
        background: var(--my-blue);
        font-weight: normal;
    }

    td {
        padding: 10px 5px;
        font-size: 13px;
    }

    td input {
        width: 60px;
        height: 30px;
        padding: 5px;
        border: 1px solid var(--my-blue);
    }

    td a {
        color: var(--my-blue);
        font-size: 12px;
    }

    td img {
        width: 80px;
        height: 80px;
        margin-right: 10px;
    }

    .total-price {
        display: flex;
        justify-content: flex-end;
    }

    .total-price table {
        border-top: 3px solid var(--my-blue);
        width: 100%;
        max-width: 400px;
        /* ESTO SIRVE PARA PONER LA TABLA A LA MISMA ALTURA DEL QUANTITY */
    }

    td:last-child {
        text-align: right;
    }

    th:last-child {
        text-align: right;
    }

    .btnComprar {
        display: inline-block;
        float: right;
        /* Alinea a la derecha */
        margin-top: 1rem;
        border-radius: .5rem;
        background: var(--light-celeste);
        color: var(--black);
        font-weight: 500;
        font-size: 1.7rem;
        cursor: pointer;
        padding: .8rem 3rem;
    }

    .btnComprar:hover {
        background: var(--celeste);
    }

    .btnSeguirComprando {
        display: inline-block;
        float: right;
        /* Alinea a la derecha */
        margin-top: 1rem;
        border-radius: .5rem;
        background: var(--light-my-blue);
        color: var(--black);
        font-weight: 500;
        font-size: 1.7rem;
        cursor: pointer;
        padding: .8rem 3rem;
        margin: 1rem;
    }

    .btnSeguirComprando:hover {
        background: var(--my-blue);
    }

    /*---------------------- cambios ---------------------- */

    /* para ajustar las imagenes */

    .image-fit {
        max-width: 50px;
        max-height: 50px;
        width: auto;
        height: auto;
        border: 1px solid #000;
        object-fit: cover;
        /* Puedes ajustar el grosor y el color del borde según tus preferencias */
    }
</Style>

<!---------------------------- cart items details  ---------------------------->
<br>
<section class="carrito" id="carrito">
    <div class="small-container cart-page">
        <h1 class="heading"> <span>Carrito de Compras</span></h1>
        <table>
            <tr>
                <th>Productos</th>
                <th>Cantidad</th>
                <th>Subtotal</th>
            </tr>
            @foreach (var item in Model.Items)
            {
                <tr>
                    <td>
                        <div class="cart-info">
                            <img src="@item.Producto.Imagen" class="d-block w-100 image-fit">
                            <div>
                                <p>@item.Producto.Nombre</p>
                                <small>Precio: S/. @item.Precio.ToString("F2")</small>
                                <br>
                                <a href="@Url.Action("QuitarDelCarrito", "Carrito", new { id = item.Id })">Quitar</a>
                            </div>
                        </div>
                    </td>
                    <td>
                        <form method="post" action="@Url.Action("ActualizarCantidad", "Carrito")" onchange="this.submit()">
                            <input type="number" name="cantidad" value="@item.Cantidad" min="1">
                            <input type="hidden" name="id" value="@item.Id">
                        </form>
                    </td>
                    <td>S/. @(((double)item.Precio * item.Cantidad).ToString("F2")) </td>
                </tr>
            }
        </table>

        <!---------------------------- TOTAL PRICE ---------------------------->
        <div class="total-price">
            <table>
                <!--<tr>
                    <td>Subtotal</td>
                    <td id="subtotal-general">S/. @Model.Subtotal.ToString("F2")</td>
                </tr>

                <tr>
                    <td>Descuento</td>
                    <td id="descuento">S/. @Model.Descuento.ToString("F2")</td>
                </tr> -->

                <tr>
                    <td>Total</td>
                    <td id="total">S/. @Model.Total.ToString("F2") (USD @totalEnUSD.ToString("F2"))</td>
                </tr>
            </table>
        </div>
        <a class="btnComprar" style="text-decoration: none;" asp-area="" asp-controller="Pago" asp-action="Create" asp-route-monto="@Model.Total">Comprar</a>
        <a class="btnSeguirComprando" style="text-decoration: none;" asp-area="" asp-controller="NoCliente" asp-action="Catalogo">Seguir comprando</a>
    </div>
</section>
@if (TempData["Error"] != null)
{
    <div class="alert alert-danger" id="MensajesVerdeRojo">
        @TempData["Error"]
    </div>
}

@* —————————————— Bloque que inyecta el console.log —————————————— *@
    @if (!string.IsNullOrEmpty(mensajeConsola))
    {
        <script>
            // Este console.log se ejecutará apenas cargue la página
            console.log('@mensajeConsola');
        </script>
    }
<!---------------------------- cart ends ---------------------------->

<!---------------------------- javascript para actualizar el carrito ---------------------------->